# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1485859657);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1485859777);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1485876368);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1485859537);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1485859417);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1485859897);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 40);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1485876169637");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1485877916637");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1485876170752");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1485879770752");
user_pref("browser.search.countryCode", "BE");
user_pref("browser.search.region", "BE");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.startup.homepage", "http://www.biblioludowb.be");
user_pref("browser.startup.homepage_override.buildID", "20170127014032");
user_pref("browser.startup.homepage_override.mstone", "51.0.1");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"print-button\",\"downloads-button\",\"panic-button\",\"home-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 3706);
user_pref("datareporting.sessions.current.main", 70);
user_pref("datareporting.sessions.current.sessionRestored", 3541);
user_pref("datareporting.sessions.current.startTime", "1485876429919");
user_pref("datareporting.sessions.current.totalTime", 6);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1485273400366,\"a\":33,\"t\":177,\"c\":true,\"m\":74,\"fp\":3276,\"sr\":2588}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1485273578036,\"a\":71,\"t\":1316,\"c\":true,\"m\":42,\"fp\":1902,\"sr\":1763}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1485859173938,\"a\":56,\"t\":1443,\"c\":true,\"m\":225,\"fp\":2179,\"sr\":5252}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1485876154429,\"a\":15,\"t\":92,\"c\":true,\"m\":313,\"fp\":3698,\"sr\":3553}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1485876247151,\"a\":15,\"t\":179,\"c\":true,\"m\":65,\"fp\":3984,\"sr\":3823}");
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("e10s.rollout.cohort", "addons-set51set1-test");
user_pref("e10s.rollout.cohortSample", "0.866850");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"aushelper@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"e10srollout@mozilla.org\":{\"version\":\"1.7\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"51.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"51.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"langpack-fr@firefox.mozilla.org\":{\"version\":\"51.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-fr@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.blocklist", "{dc572301-7619-498c-a57d-39143191b318}");
user_pref("extensions.e10s.rollout.hasAddon", true);
user_pref("extensions.e10s.rollout.policy", "51set1");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "belgiumeid%40eid.belgium.be:1.0.22,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:51.0.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1485859658);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "51.0.1");
user_pref("extensions.lastPlatformVersion", "51.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-profile\":{\"belgiumeid@eid.belgium.be\":{\"d\":\"/home/modele/.mozilla/firefox/mwad0hks.default/extensions/belgiumeid@eid.belgium.be.xpi\",\"e\":true,\"v\":\"1.0.22\",\"st\":1485876248000}},\"app-system-defaults\":{\"aushelper@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1485482662000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1485482663000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.7\",\"st\":1485482662000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1485482663000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"51.0.1\",\"st\":1485482662000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"51.0.1\",\"st\":1485483002000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"51.0.1\",\"st\":1485483002000},\"langpack-fr@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-fr@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"51.0.1\",\"st\":1485483008000}},\"app-system-share\":{\"belgiumeid@eid.belgium.be\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/belgiumeid@eid.belgium.be.xpi\",\"e\":false,\"v\":\"1.0.22\",\"st\":1485170085000}}}");
user_pref("idle.lastDailyNotification", 1485860073);
user_pref("intl.accept_languages", "fr,fr-be,fr-fr,en-us,en");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1485273464);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170127014032");
user_pref("media.gmp-manager.lastCheck", 1485859240);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1485273953);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.language.disable_button.down", false);
user_pref("services.blocklist.addons.checked", 1485854341);
user_pref("services.blocklist.clock_skew_seconds", 5436);
user_pref("services.blocklist.last_etag", "\"1485301408557\"");
user_pref("services.blocklist.last_update_seconds", 1485854341);
user_pref("services.blocklist.onecrl.checked", 1485854341);
user_pref("services.blocklist.plugins.checked", 1485854341);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1485273953);
user_pref("toolkit.startup.last_success", 1485876429);
user_pref("toolkit.telemetry.cachedClientID", "1c6e8769-809b-4ce8-8603-a59009286695");
user_pref("toolkit.telemetry.previousBuildID", "20170127014032");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
